### ISSUE TITLE
.gitignore 에 **/migrations 하면 VSCode에서 반영되나요???

### ISSUE THREAD

**Issue by shonjiho** [shonjiho/GodReads#6]
저는 계속 안되네요.
![image](https://user-images.githubusercontent.com/20085849/73911285-ee923200-48f4-11ea-96ae-5e1862a04928.png)

**Comment by pleielp** [comment]
저는 문제없이 돌아가네요.

**Comment by pleielp** [comment]
![image](https://user-images.githubusercontent.com/11135572/73923773-c0b9e700-490e-11ea-948f-8a808e315de4.png)

**Comment by shonjiho** [comment]
알겠습니다!
